### ISSUE TITLE
Can't add Wifi Button+

### ISSUE THREAD

**Issue by frusciantee** [cgHome/ch.mystrom.smarthome#1]
I just tried to add the myStrom Wifi Button+, but can't it add it as a device to Homey.
I have installed the button in the myStrom app and have it in the same Wifi as Homey, but every time I try to install it in Homey (tried for a couple of hours now), it pretty much instantly shows me the "No new devices have been found." message.
Is there anything I am doing wrong or is this a known issue?

**Comment by cgHome** [comment]
Hi frusciantee, I need to investigate this further, but there seems to be a problem between Homey v1 and v2. (I am still on version v1 due to compatibility problems and don't have a test system either)

**Comment by frusciantee** [comment]
Thank you very much for taking care of this, I would love to be able to use my Wifi Button+.

**Comment by cgHome** [comment]
Fixed & Relased  v0.3.0
